---
/config/smtp_servers:
  get:
    x-mojo-to: Config::SMTP::Servers#list
    operationId: listSMTPServers
    tags:
      - smtp_servers
    summary: List SMTP servers
    produces:
      - application/json
    parameters:
      - $ref: "../swagger.yaml#/parameters/match"
      - $ref: "../swagger.yaml#/parameters/order_by"
      - $ref: "../swagger.yaml#/parameters/page"
      - $ref: "../swagger.yaml#/parameters/per_page"
      - $ref: "../swagger.yaml#/parameters/q_param"
      - $ref: "../swagger.yaml#/parameters/q_body"
      - $ref: "../swagger.yaml#/parameters/request_id_header"
    responses:
      "200":
        description: A list of SMTP servers
        schema:
          type: array
          items:
            $ref: "../swagger.yaml#/definitions/smtp_server"
      "403":
        description: Access forbidden
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "500":
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "503":
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        parameters: manage_smtp_servers
  post:
    x-mojo-to: Config::SMTP::Servers#add
    operationId: addSMTPServer
    tags:
      - smtp_servers
    summary: Add SMTP server
    parameters:
      - name: body
        in: body
        description: A JSON object representing a new SMTP server configuration
        required: true
        schema:
          $ref: "../swagger.yaml#/definitions/smtp_server"
    produces:
      - application/json
    responses:
      "201":
        description: An SMTP server object
        schema:
          $ref: "../swagger.yaml#/definitions/smtp_server"
      "401":
        description: Authentication required
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "403":
        description: Access forbidden
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "409":
        description: Conflict in creating resource
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "500":
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "503":
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        parameters: manage_smtp_servers
"/config/smtp_servers/{smtp_server_id}":
  get:
    x-mojo-to: Config::SMTP::Servers#get
    operationId: getSMTPServer
    tags:
      - smtp_servers
    summary: Get SMTP server
    parameters:
      - $ref: "../swagger.yaml#/parameters/smtp_server_id_pp"
    produces:
      - application/json
    responses:
      "200":
        description: An SMTP server object
        schema:
          $ref: "../swagger.yaml#/definitions/smtp_server"
      "404":
        description: Object not found
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "409":
        description: Conflict updating resource
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "500":
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "503":
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        parameters: manage_smtp_servers
  put:
    x-mojo-to: Config::SMTP::Servers#update
    operationId: updateSMTPServer
    tags:
      - smtp_servers
    summary: Update SMTP server
    parameters:
      - $ref: "../swagger.yaml#/parameters/smtp_server_id_pp"
      - name: body
        in: body
        description: An SMTP server object
        required: true
        schema:
          $ref: "../swagger.yaml#/definitions/smtp_server"
    produces:
      - application/json
    responses:
      "200":
        description: An SMTP server object
        schema:
          $ref: "../swagger.yaml#/definitions/smtp_server"
      "401":
        description: Authentication required
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "403":
        description: Access forbidden
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "404":
        description: Object not found
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "500":
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "503":
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        parameters: manage_smtp_servers
  delete:
    x-mojo-to: Config::SMTP::Servers#delete
    operationId: deleteSMTPServer
    tags:
      - smtp_servers
    summary: Delete SMTP server
    parameters:
      - $ref: "../swagger.yaml#/parameters/smtp_server_id_pp"
    produces:
      - application/json
    responses:
      "204":
        description: SMTP server deleted
      "401":
        description: Authentication required
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "403":
        description: Access forbidden
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "404":
        description: Object not found
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "500":
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      "503":
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        parameters: manage_smtp_servers
