---
/erm/config:
  get:
    x-mojo-to: ERM#config
    operationId: getERMconfig
    description: This resource returns a list of options needed for the ERM Vue app
    summary: get the ERM config
    tags:
      - ERM
    produces:
      - application/json
    responses:
      200:
        description: The ERM config
        schema:
          $ref: "../swagger.yaml#/definitions/erm_config"
      400:
        description: Bad request
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      403:
        description: Access forbidden
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      500:
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      503:
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        erm: 1
