---
# General field configuration
general:
  _all:
    type: string
    analyzer: analyser_standard
  properties:
    record:
      store: true
      type: text
# Search fields
search:
  boolean:
    type: boolean
    null_value: false
  integer:
    type: integer
    null_value: 0
  stdno:
    type: text
    analyzer: analyser_stdno
    search_analyzer: analyser_stdno
    fields:
      phrase:
        type: text
        analyzer: analyser_stdno
        search_analyzer: analyser_stdno
      raw:
        type: keyword
    copy_to: _all
  default:
    type: text
    analyzer: analyser_standard
    search_analyzer: analyser_standard
    fields:
      phrase:
        type: text
        analyzer: analyser_phrase
        search_analyzer: analyser_phrase
      raw:
        type: keyword
      lc_raw:
        type: keyword
        normalizer: my_normalizer
    copy_to: _all
# Facets
facet:
  default:
    type: keyword
# Suggestible
suggestible:
  default:
    type: completion
    analyzer: simple
    search_analyzer: simple
# Sort
sort:
  default:
    type: text
    analyzer: analyser_phrase
    search_analyzer: analyser_phrase
    fields:
      phrase:
        type: keyword
