modules:
  acqui:
    pendingorders:
      pendingt:
        -
          columnname: basket
        -
          columnname: basketgroup
        -
          columnname: order_line
        -
          columnname: summary
        -
          columnname: view_record
        -
          columnname: quantity
        -
          columnname: unit_cost
        -
          columnname: order_cost
        -
          columnname: fund
        -
          columnname: receivetransfer
        -
          columnname: canceldelete

    histsearch:
      histsearcht:
        -
          columnname: order_line
        -
          columnname: status
        -
          columnname: basket
        -
          columnname: basket_creator
        -
          columnname: basket_group
        -
          columnname: invoice_number
        -
          columnname: summary
        -
          columnname: vendor
        -
          columnname: placed_on
        -
          columnname: received_on
        -
          columnname: quantity_received
        -
          columnname: pending_order
        -
          columnname: unit_cost
        -
          columnname: fund

    lateorders:
      late_orders:
        -
          columnname: checkbox
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: order_date
        -
          columnname: estimated_delivery_date
        -
          columnname: vendor
        -
          columnname: information
        -
          columnname: total_cost
        -
          columnname: basket
        -
          columnname: basket_group
        -
          columnname: library
        -
          columnname: fund
        -
          columnname: claims_count
        -
          columnname: claimed_date

  admin:
    currency:
      currencies-table:
        -
          columnname: currency
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: rate
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: symbol
        -
          columnname: iso_code
          is_hidden: 1
        -
          columnname: last_updated
        -
          columnname: active
        -
          columnname: actions

  cataloguing:
    additem:
      itemst:
        # NOTE: These columns are in the same order as kohastructure.sql, and contain all items
        # columns except for the following internal/obsolete fields: stack, more_subfields_xml,
        # cn_sort, permanent_location, itemlost_on, withdrawn_on, issues, renewals and reserves.
        -
          columnname: barcode
        -
          columnname: dateaccessioned
        -
          columnname: booksellerid
        -
          columnname: homebranch
        -
          columnname: price
        -
          columnname: replacementprice
        -
          columnname: replacementpricedate
        -
          columnname: datelastborrowed
        -
          columnname: datelastseen
        -
          columnname: stack
        -
          columnname: notforloan
        -
          columnname: damaged
        -
          columnname: itemlost
        -
          columnname: withdrawn
        -
          columnname: itemcallnumber
        -
          columnname: coded_location_qualifier
        -
          columnname: restricted
        -
          columnname: itemnotes
        -
          columnname: itemnotes_nonpublic
        -
          columnname: holdingbranch
        -
          columnname: paidfor
        -
          columnname: timestamp
        -
          columnname: location
        -
          columnname: onloan
        -
          columnname: cn_source
        -
          columnname: ccode
        -
          columnname: materials
        -
          columnname: uri
        -
          columnname: itype
        -
          columnname: enumchron
        -
          columnname: copynumber
        -
          columnname: stocknumber

  members:
    fines:
      account-fines:
        -
          columnname: date
        -
          columnname: description
        -
          columnname: note
        -
          columnname: amount
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: amountoutstanding
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: actions
          cannot_be_toggled: 1
          cannot_be_modified: 1

    member:
      memberresultst:
        -
          columnname: checkbox
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: cardnumber
        -
          columnname: name
        -
          columnname: dateofbirth
        -
          columnname: category
        -
          columnname: library
        -
          columnname: expires_on
        -
          columnname: od_checkouts
        -
          columnname: fines
        -
          columnname: circ_notes
        -
          columnname: actions
          cannot_be_toggled: 1
          cannot_be_modified: 1

    moremember:
      issues-table:
        -
          columnname: sort_order
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: todays_or_previous_checkouts
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date_unformatted
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date
        -
          columnname: title
        -
          columnname: item_type
        -
          columnname: location
        -
          columnname: homebranch
        -
          columnname: checkout_on
        -
          columnname: checkout_from
        -
          columnname: callno
        -
          columnname: charge
        -
          columnname: fine
        -
          columnname: price
        -
          columnname: renew
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: checkin
        -
          columnname: export
          cannot_be_toggled: 1
          cannot_be_modified: 1

  reports:
    lostitems:
      lostitems-table:
        -
          columnname: title
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: author
        -
          columnname: lostcode
        -
          columnname: barcode
        -
          columnname: callnumber
        -
          columnname: datelastseen
        -
          columnname: price
        -
          columnname: replacementprice
        -
          columnname: library
        -
          columnname: itemtype
        -
          columnname: current_location
        -
          columnname: location
        -
          columnname: notes

  circ:
    circulation:
      issues-table:
        -
          columnname: sort_order
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: todays_or_previous_checkouts
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date_unformatted
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date
        -
          columnname: title
        -
          columnname: item_type
        -
          columnname: location
        -
          columnname: homebranch
        -
          columnname: checkout_on
        -
          columnname: checkout_from
        -
          columnname: callno
        -
          columnname: charge
        -
          columnname: fine
        -
          columnname: price
        -
          columnname: renew
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: checkin
        -
          columnname: export
          cannot_be_toggled: 1
          cannot_be_modified: 1

    returns:
      checkedintable:
        -
          columnname: due_date
        -
          columnname: title
        -
          columnname: author
        -
          columnname: barcode
        -
          columnname: homelibrary
        -
          columnname: holdinglibrary
        -
          columnname: location
        -
          columnname: itemcallnumber
        -
          columnname: dateaccessioned
          is_hidden: 1
        -
          columnname: itype
        -
          columnname: borrower
        -
          columnname: itemnote

    view_holdsqueue:
      holds-table:
        -
          columnname: title
        -
          columnname: collection:
        -
          columnname: document_type
        -
          columnname: callnumber
        -
          columnname: copynumber
        -
          columnname: enumeration
        -
          columnname: barcode
        -
          columnname: patron
        -
          columnname: send_to
        -
          columnname: date
        -
          columnname: notes

    holds:
      holds-to-pull:
        -
          columnname: pull_items
        -
          columnname: avalaible_items
        -
          columnname: patrons
        -
          columnname: patron
        -
          columnname: libraries
        -
          columnname: earliest_hold_at
        -
          columnname: call_numbers
        -
          columnname: title
        -
          columnname: copy_numbers
        -
          columnname: enumeration
        -
          columnname: itemtypes
        -
          columnname: locations
        -
          columnname: sublocations
        -
          columnname: collections
        -
          columnname: genres
        -
          columnname: itemnotes
        -
          columnname: hold_date
